#端口号
server.port: 8080

#数据源
spring:
  datasource:
    url: jdbc:mysql://112.74.174.102:3306/pms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#sql映射地址   
mybatis:
   mapper-locations: classpath:mapper/*.xml